language: node_js
node_js:
  - 'lts/*'
  - '10'
  - '9'
  - '8'
matrix:
  include:
    - node_js: 'lts/*'

install: cd client && [ -f ./package-lock ] && npm ci || npm install && cd ..
script: cd client && npm test && cd ..

# Create a NPM Audit job
jobs:
  include:
    - stage: NPM audit
      script: cd client && npm audit
      node_js: 'lts/*'

# Run npm audit before tests
stages:
  - NPM audit
  - test